version: 2

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 25
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: "/src/MunicipalityRegistry.Api.CrabImport"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: "/src/MunicipalityRegistry.Api.Extract"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: "/src/MunicipalityRegistry.Api.Legacy"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: "/src/MunicipalityRegistry.Api.Oslo"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: "/src/MunicipalityRegistry.Projector"
  schedule:
    interval: weekly
