// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipalityRegistry.Projections.Integration;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MunicipalityRegistry.Projections.Integration.Migrations
{
    [DbContext(typeof(IntegrationContext))]
    [Migration("20240417143638_AddIsFlemishRegion")]
    partial class AddIsFlemishRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("DesiredState")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DesiredStateChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionStates", "integration_municipality");
                });

            modelBuilder.Entity("MunicipalityRegistry.Projections.Integration.MunicipalityGeometry", b =>
                {
                    b.Property<string>("NisCode")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("nis_code")
                        .IsFixedLength();

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.HasKey("NisCode");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("NisCode");

                    b.ToTable("municipality_geometries", "integration_municipality");
                });

            modelBuilder.Entity("MunicipalityRegistry.Projections.Integration.MunicipalityLatestItem", b =>
                {
                    b.Property<Guid>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<bool?>("FacilityLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_dutch");

                    b.Property<bool?>("FacilityLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_english");

                    b.Property<bool?>("FacilityLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_french");

                    b.Property<bool?>("FacilityLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_german");

                    b.Property<bool>("IsFlemishRegion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasColumnName("is_flemish_region")
                        .HasComputedColumnSql("nis_code LIKE '1%' OR nis_code LIKE '3%' OR nis_code LIKE '4%' OR nis_code LIKE '7%' OR nis_code LIKE '23%' OR nis_code LIKE '24%'", true);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<string>("NameDutch")
                        .HasColumnType("text")
                        .HasColumnName("name_dutch");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("text")
                        .HasColumnName("name_english");

                    b.Property<string>("NameFrench")
                        .HasColumnType("text")
                        .HasColumnName("name_french");

                    b.Property<string>("NameGerman")
                        .HasColumnType("text")
                        .HasColumnName("name_german");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("namespace");

                    b.Property<string>("NisCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("nis_code")
                        .IsFixedLength();

                    b.Property<bool?>("OfficialLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_dutch");

                    b.Property<bool?>("OfficialLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_english");

                    b.Property<bool?>("OfficialLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_french");

                    b.Property<bool?>("OfficialLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_german");

                    b.Property<string>("OsloStatus")
                        .HasColumnType("text")
                        .HasColumnName("oslo_status");

                    b.Property<string>("PuriId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puri_id");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("VersionAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_as_string");

                    b.Property<DateTimeOffset>("VersionTimestampAsDateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_timestamp");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("NameDutch");

                    b.HasIndex("NameEnglish");

                    b.HasIndex("NameFrench");

                    b.HasIndex("NameGerman");

                    b.HasIndex("NisCode");

                    b.HasIndex("OsloStatus");

                    b.HasIndex("Status");

                    b.ToTable("municipality_latest_items", "integration_municipality");
                });

            modelBuilder.Entity("MunicipalityRegistry.Projections.Integration.MunicipalityVersion", b =>
                {
                    b.Property<long>("Position")
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    b.Property<string>("CreatedOnAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_on_as_string");

                    b.Property<DateTimeOffset>("CreatedOnTimestampAsDateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_timestamp");

                    b.Property<bool?>("FacilityLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_dutch");

                    b.Property<bool?>("FacilityLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_english");

                    b.Property<bool?>("FacilityLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_french");

                    b.Property<bool?>("FacilityLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_german");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<string>("NameDutch")
                        .HasColumnType("text")
                        .HasColumnName("name_dutch");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("text")
                        .HasColumnName("name_english");

                    b.Property<string>("NameFrench")
                        .HasColumnType("text")
                        .HasColumnName("name_french");

                    b.Property<string>("NameGerman")
                        .HasColumnType("text")
                        .HasColumnName("name_german");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("namespace");

                    b.Property<string>("NisCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("nis_code")
                        .IsFixedLength();

                    b.Property<bool?>("OfficialLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_dutch");

                    b.Property<bool?>("OfficialLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_english");

                    b.Property<bool?>("OfficialLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_french");

                    b.Property<bool?>("OfficialLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_german");

                    b.Property<string>("OsloStatus")
                        .HasColumnType("text")
                        .HasColumnName("oslo_status");

                    b.Property<string>("PuriId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puri_id");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("VersionAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_as_string");

                    b.Property<DateTimeOffset>("VersionTimestampAsDateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_timestamp");

                    b.HasKey("Position");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("NisCode");

                    b.HasIndex("VersionTimestampAsDateTimeOffset");

                    b.ToTable("municipality_versions", "integration_municipality");
                });
#pragma warning restore 612, 618
        }
    }
}
